enum class GameEvent {
    REPLAY_GAME,
    EXIT_TO_MENU,
    CREATE_POWER_UP,
    ADD_SCORE_ONE,
    ADD_SCORE_ONE_HALF,
    ADD_SCORE_TWO,
    ADD_SCORE_TWO_HALF,
    CONTINUE_GAME_ONE,
    CONTINUE_GAME_TWO,
}